### ISSUE TITLE
Unhandled Exception: SQL error or missing database

### ISSUE THREAD

**Issue by sirlancelot** [nels-o/toaster#8]
A colleague of mine was having this issue on Windows 10 when running this through `gulp-notify`. The following error is shown when trying to notify.

```
Unhandled Exception: System.Exception: SQL error or missing database (Exception from HRESULT: 0x87AF0001)
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at toast.Program.ShowToast(String title, String message, String imageURI, Boolean sound)
   at toast.Program.Main(String[] args)
```

We traced the issue down to a corrupted Windows 10 notification database. Go to `~\AppData\Local\Microsoft\Windows\Notifications` and delete the three `*.db*` files. You may need to close & restart Explorer.

Perhaps an enhancement which can be made to this app would be to catch this exception and output something a little more helpful.

**Comment by nels-o** [comment]
Oh, interesting. I'll think a bit about how toaster should handle that sort of exception.

**Comment by sirlancelot** [comment]
Thanks @nels-o! My team has found this app quite useful. Thanks for making it!
